language: python

python:
  - "3.5"

addons:
  apt:
    packages:
      - espeak
      - mbrola
      - mbrola-*
      - libasound-dev

install:
  - python setup.py install

script:
  - python setup.py test
