language: python

python:
  - "3.5"

addons:
  apt:
    packages:
      - espeak
      - mbrola
      - mbrola-*
      - libasound2-dev


install:
  - pip install --user -r requirements.txt

script:
  - python setup.py test
