language: python
dist: trusty
sudo: required

python:
  - "3.5"

addons:
  apt:
    packages:
      - espeak
      - mbrola
      - mbrola-*
      - libjack-jackd2-dev
      - portaudio19-dev

script:
  - python setup.py test
